export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Projects',
    headline: 'Recent Work',
    description: 'A food vlogger, short for "food video blogger" or "food content creator," is an individual who creates and shares video content primarily focused on food-related topics. These content creators are often passionate about food and culinary experiences, and they use various online platforms, such as YouTube, Instagram, TikTok, and blogs, to connect with their audience',
    buttonLabel: 'Get In Touch',
    imgStart: false,
    img: require('../../images/food-vlog.png'),
    alt: 'Rocket',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Company',
    headline: 'Spark Food Dome',
    description: 'A food vlogger, short for "food video blogger" or "food content creator," is an individual who creates and shares video content primarily focused on food-related topics. These content creators are often passionate about food and culinary experiences, and they use various online platforms, such as YouTube, Instagram, TikTok, and blogs, to connect with their audience',
    buttonLabel: "We're Hiring! Click Here To Apply",
    imgStart: true,
    img: require('../../images/company-logo.png'),
    alt: 'Planet',
    dark: false,
    primary: false,
    darkText: true,
};
